package com.techelevator.tests;

import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.rowset.SqlRowSet;
import org.junit.Before;
import org.junit.Test;
import junit.framework.Assert;

import com.techelevator.model.Whiskey;



public class JDBCWhiskeyDAOIntegrationTesting extends DAOIntegrationTesting {
	
	private WhiskeyDao dao;
	private JdbcTemplate jdbcTemplate;


	@Before
	public void setup() {
		
		jdbcTemplate = new JdbcTemplate(dataSource);
		dao = new JdbcWhiskeyDao(dataSource);
		
	}
	
	//testWhiskey1 = createWhiskey(whiskey_id, brand, price, taste_rating, nose_rating, color_rating ,body_rating, finish_rating, price__rating, overall_rating);
	
	
	@Test 
	public void save_whiskey_adds_whiskey() {
		
		Whiskey whiskey = createWhiskey();
		
		dao.saveWhiskey(whiskey);
		
		String sql2 = "";
		SqlRowSet result = jdbcTemplate.queryForRowSet(sql2, "test");
		result.next();
		String dataReceived = result.getString("");
		
		Assert.assertEquals("test", dataReceived);
	}
	
	//Simulating user entering 
	private Whiskey createWhiskey() {
		
		Whiskey whiskey = new Whiskey();
		//whiskey_id implied and generated by db
		whiskey.setBrand("Hotel Brand Somm");
		whiskey.setPrice(50);
//		whiskey.setTasteRating(5);
//		whiskey.setNoseRating(5);
//		whiskey.setColorRating(5);
//		whiskey.setBodyRating(5);
//		whiskey.setFinishRating(5);
//		whiskey.setPriceRating(5);
//		whiskey.setOverallRating(5);
		
		return whiskey;
		
}
}