package com.techelevator.tests;

import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.rowset.SqlRowSet;

import com.techelevator.model.JdbcWhiskeyDao;
import com.techelevator.model.Whiskey;
import com.techelevator.model.WhiskeyDao;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;


public class JDBCWhiskeyDAOIntegrationTesting extends DAOIntegrationTesting {
	
	private WhiskeyDao dao;
	private JdbcTemplate jdbcTemplate;


	@Before
	public void setup() {
		
		jdbcTemplate = new JdbcTemplate(dataSource);
		dao = new JdbcWhiskeyDao(dataSource);
		
	}
	
	//testWhiskey1 = createWhiskey(whiskey_id, brand, price, taste_rating, nose_rating, color_rating ,body_rating, finish_rating, price__rating, overall_rating);
	//INSERT INTO whiskey (whiskey_id, brand, price, taste_rating, nose_rating, body_rating, finish_rating, price__rating, overall_rating)
	//VALUES (3, 'test', 13, 4, 5, 3, 2, 3, 4);
	@Test
	public void get_all_whiskeys_returns_all_whiskeys() {
		List<Whiskey>whiskeyList = dao.getAllBrandAndPriceWhiskey();
		
		int whiskeyListOriginalSize = whiskeyList.size();
		
		String sql = "INSERT INTO whiskey(whiskey_id, brand, price) " +
				"VALUES (default, 'Tech Elevator Whiskey', 6);";
		
		jdbcTemplate.update(sql);
		
		List<Whiskey> updatedWhiskeyList = dao.getAllBrandAndPriceWhiskey();
		
		int whiskeyListNewSize = updatedWhiskeyList.size();
		
		Assert.assertEquals(whiskeyListOriginalSize + 1, whiskeyListNewSize);
	}

	
	@Test 
	public void save_whiskey_adds_whiskey() {
		
		Whiskey whiskey = createWhiskey();
		
		dao.saveWhiskey(whiskey);
		
		String sql2 = "SELECT brand, price " +
		"FROM whiskey WHERE brand = ?;";
		SqlRowSet result = jdbcTemplate.queryForRowSet(sql2, "test");
		result.next();
		String dataReceived = result.getString("brand");
		
		Assert.assertEquals("test", dataReceived);
	}
	
	//Simulating user entering 
	private Whiskey createWhiskey() {
		
		Whiskey whiskey = new Whiskey();
		//whiskey_id implied and generated by db
		whiskey.setBrand("Hotel Brand Somm");
		whiskey.setPrice(50);
//		whiskey.setTasteRating(5);
//		whiskey.setNoseRating(5);
//		whiskey.setColorRating(5);
//		whiskey.setBodyRating(5);
//		whiskey.setFinishRating(5);
//		whiskey.setPriceRating(5);
//		whiskey.setOverallRating(5);
		
		return whiskey;
		
}
}